all:			RegisterClient.class RegisterServer.class \
			RegisterInterfaceClient.class RegisterInterfaceServer.class

RegisterInterfaceClient.class:	RegisterInterfaceClient.java
			@javac RegisterInterfaceClient.java

RegisterInterfaceServer.class:	RegisterInterfaceServer.java
			@javac RegisterInterfaceServer.java

RegisterClient.class:	RegisterClient.java
			@javac RegisterClient.java

RegisterServer.class:	RegisterServer.java
			@javac RegisterServer.java

clean:
			@rm -f *.class *~

